language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
    - downloads
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_AUTOMATIC_APPLE=true
  # Our build takes too long for one job, so split targets across multiple jobs
  # triplets come from
  # using BinaryBuilder; triplet.(supported_platforms())
  matrix:
    - TARGET=i686-linux-gnu-gcc7
    - TARGET=x86_64-linux-gnu-gcc7
    - TARGET=aarch64-linux-gnu-gcc7
    - TARGET=arm-linux-gnueabihf-gcc7
    - TARGET=powerpc64le-linux-gnu-gcc7
    - TARGET=i686-linux-musl-gcc7
    - TARGET=x86_64-linux-musl-gcc7
    - TARGET=aarch64-linux-musl-gcc7
    - TARGET=arm-linux-musleabihf-gcc7
    - TARGET=x86_64-apple-darwin14
    - TARGET=x86_64-unknown-freebsd11.1
    - TARGET=i686-w64-mingw32-gcc7
    - TARGET=x86_64-w64-mingw32-gcc7
sudo: required

jobs:
  include:
    - stage: regenerate build.jl
      script: julia --color=yes build_tarballs.jl --only-buildjl
      if: tag IS present

# Before anything else, get the latest versions of things
before_script:
  - julia --color=yes -e 'using Pkg;
      Pkg.add(PackageSpec(name="BinaryProvider", rev="v0.5.8"));
      Pkg.add(PackageSpec(name="BinaryBuilder", rev="v0.1.4"))'

script:
  - julia --color=yes build_tarballs.jl $TARGET

deploy:
    provider: releases
    api_key:
      secure: 594kCrKRSdhSKvgjjiHCqdVPYrsE4ixXARHdLd2Z05AUBSL0FdkzARupGqhGV/HyLqKvFgO6DrQo0nbOkPJuwtSWqR8JkYYC5GH2ymD/goNydoFUxCBj6iVLW1d1n7zIu7Ju4KcXZqwQIh4aFTKcJ65WO4U+sY5OOhOoaPIPPltoL2e5z3ZcENEYrehzA8WFydPI/oRQHRLkm/AZKcKIkHrCy5PeQu49fzIJ+hYqufmi7D04dDPOWAP7FAx8IOoXBIImPl5hKgWt1ajPXNC5IEctFVICrZrCZ/ZxpIJAlTJCymsu9gmZ0W6nEhTuRqEPwSIu3gt279bXXShGOzpDLJMQCCQkio1HkxtpwSkzauExzfDAgYB5pr1QyaZxgj7ATo0XO9MkrcIPZdzRAokuAQXwQct4DMN2DwEKfGIGKi8DNp0pNb/wBR2QKjBg3vT0uLIQW5P5h7pDt822oDDAo/rnASJHXx+Kgd+qrnr2ohjouI6IcgLOexONWL75aF/7ZZUrPucXpY43XP1v7C0XwE65Cnz5YiJnI3JtNYmONQs93TdPBbvGveBVDnOe7nIg6ng43echtH0eSrYJazqu9Lt9ydOYadTlnZJOnmw90gz0uNoNmiX+sv9fC1PPHGG4qZANmkS8oclP0UVV9ynar+qSqTb1ysetM8ZApJUXRqE=
    file_glob: true
    file: products/*
    skip_cleanup: true
    on:
        repo: JuliaGeo/GDALBuilder
        tags: true
